language: node_js
node_js:
- '8'
env:
  global:
  - HEROKU_APP_ID=sentry-demos-react
  - SENTRY_ORG=testorg-az
  - SENTRY_PROJECT=sentry-demos-react
  - secure: SzYLq3c0L+aHfGaHYiR894FwmebCNxekZIAsQIc7Xih89a3lsMj2l0/EdfD4Ofy8SxuLi68I1di0HTB6gPpR+ElxxgZi7BgysNQjs5YKp1yYdb8XdbF9Jn4dOA66j8Bvfg+UBgCkCV9Et9ZBHhNKvEWY9L1+rDrX226MbLKwms4YWfXLXYXRmJeb3P0BlIQqEeV+tMamrwrDxM7Lh02vysH3wVw4TEx6+8Vr2kZmjCOOq9Q/YXOoI0FcI8v1NggoKqQFIBa8r1Ke8S08caldQHhH4KAQlrqThJ9Bw+BhoIPpt94DiH3KRdm8Z6pv0uOkT4Cu11q5d+jh12ho/vsIZMvTurn8AimJmLQlGThAj3t+fPItz1nYBzqbTPRqDqvwMcozKsaXcYd0BdyiTwHf22yqZeru1MHO3x+5jJbnVgRAaxd8ucois1OMiANUhQ83qPd6PnJeBubcUcDUJ++oUiThB/M1vH7FfJDmdO0Qznqs3+ngdCqrMn5OjqOdCxvoKn5DR7fSSQovp6AG6wEkU7CDjXkFmKBKHQyFgkqGOxb3Gs7zfgCV6W9RFwJmIh066j9irBPN4gnX40TXHINQQJIXGJgzqInaQULD/Fod0R2G3c5suWB3B8gNZzalHrXhkFkliKTBqZ7rD+7q0PFoiL038tHH4kYC9d0tceyCKKM=
  - secure: gjPPC5Zpkj/+G/83VgQBcwFZsC/Nz7c7ghWaK02P1zQwE4aCdRdMV9Mh5ERT0mHtOc7cS0+6/zgbGJqmn8NLZMcxZIcWUMb+a0QFJSqgUfg0ETYpng0s8Y7ODDK9EddfqnNqlEOOk9fzWPIhp5mpD4f6Mf21lUvokUBHGTbz7/XbHFh6eEe82ZASY2IHea3rArQlK51UUxlS6vld+Fry2KuC/WOZK4nKa3gksBd9U5I0smMl9bSLw6BJ4zx/W9rPmr5K4IKTOJZxuODeu64Y1I/RN+n0O148qKcQ6w0rWKn29nm8xMEATe0E5p4KHIn0PFiGOd757GPHPT66YQz2eqREARTkCz7fv5pgfJjT9K5p3E4hTvUFUwaSHpC8fQr6iGdjfJ+D6cawnl/fFJMATZfUYHc3b5n62b+CrtLkCSlUL5mzcHPnLb6jJyAESdFxyjXakjLRR2QdM6b3zRSBpv0K9iXQG18uJ780/6b6NNEqDM0QcHMYVKQIl2acy2WKQlJPMEoTcdl5rmJ5dWkijrAVDK8g0w8DIMTFh1UNE/eXu7XV/AyGFJgo51mzUbiOk/S22hbwgWjxioN6X+F7eZL8bx+vf/7qVlpoHHddPfVSF3QUa4YLx1WYW66QX7Tphh4hDCzI1gycrmkB/+huMh6OMKHWhfDiI/GlMOGvMzw=
before_install:
- npm install -g sentry-cli-binary
deploy:
  provider: heroku
  api_key:
    secure: y+OoPqaSWjFVoq8NoeudT1wFwTCFe3I/EHdfSIweKLPZdbaNa9qOa0y8OtxTZdn5cPuFvrA03OfZba1MY4MBOq+QIyp8z8MhgJFIIsW8eT+MIsdSo7fZBPzoAUz00+xARrl0bmYO4FsuBiXUh35VAV9nT0njHMC2TfIvga1oAH8pOrXcYhBOflNmViG1YxP7eAtIGM1TZx3c1tWp6n4mLdfFgXNOmbGmoTJ6gmVjHAVofcsg2TZxIgHsIctydTBfRsoOVnGKhdr6XLqHU6vkViC4NGA/9V48H2GHfHL6rgUkv+tVlkdrs9DQsRsjNNrBQGejKllRetHZxKGZFD4mxg5/MiIZbn9GnmncbPhokhnPO0OB7StKdvwMuyBV1OkB2rGVFxdhbooIzKlIPzOaSKiZuHO4PeFMnXmVzKFSSZpqhyM9EHXvrsG5UWkTEdTZIAoqn2xQ8cAozIVE0RY7t7Qx2X/XJIUpiE5RmnVbQv0x4h2tBLzJmIQEWZm8T2xP+nHCgwjZi6ZXcjA6My+6s2jwL5hUGZRJzBlgUwRkkRwUiHxXnXy/qnQeKrRtTjrN+mb+JGFTqB0xuxDYEx2keyNAwkmnMq2U36Myh9boo90H0eWC7NzQzAZ2gl+cowxS2eUtKb5/NzLWPZ/vhSUbYO2RGa28DlZspn6M3CP54fw=
  app: sentry-demos-react
  on:
    repo: sentry-demos/react
